### ISSUE TITLE
Use imageio to deal with the ffmpeg dependency

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#139]
As raised by @solaris573 in issue #23 we can use the imageio library to download ffmpeg if it can't be found on the system, thus dodging that as a dependency the user has to separately install.

**Comment by shuttle1987** [comment]
I think as a user-installed library this could work well. For server deployments it could cause a few issues, for example I'm not sure how nicely this will play with or CI pipeline (TravisCI) for example?

**Comment by oadams** [comment]
I think it will probably work fine on Travis, but that of course should be empirically tested.

**Comment by shuttle1987** [comment]
It turns out that as per changes in #197 we can just install ffmpeg on TravisCI directly.

**Comment by shuttle1987** [comment]
I actually don't like this approach for dealing with the ffmpeg dependency in packages we put together because it can lead to a situation where the version installed will depend on what gets installed at runtime. This may lead to situations where the versions behave differently.

It also presumes internet access that can open an outbound connection, which may not be the case. For example if running on a server egress connections may be blocked or any other number of issues could be present that make the install fail at runtime,

In the case of someone just running it on their local machine it may work out OK, but I'd rather specify versions exactly for reasons of determinism.

**Comment by shuttle1987** [comment]
Given that we likely want to pin dependencies I'm against this way of handling the dependency. Reopen if needed.

**Comment by shuttle1987** [comment]
If it turns out that this has utility for windows installs I'd be very happy to have that conversation. Thanks again @solaris573 for your code suggestion.
