### ISSUE TITLE
Pylinting

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#15]

**Comment by shuttle1987** [comment]
I think it is a good idea to add the Pylint error check into the Tox pipeline. This way any errors detected by Pylint will immediately show up.

**Comment by shuttle1987** [comment]
Pylint checking for errors has been done in #48

**Comment by oadams** [comment]
I'll close this up once I clear out the pylint errors.

**Comment by shuttle1987** [comment]
Once this is done I generally tend to put the `pylint -E` step before the unit test runner in the tox pipeline as it will catch some errors with tests as well.

**Comment by oadams** [comment]
Done!

**Comment by shuttle1987** [comment]
Many of the pylint warnings are good to deal with, the convention ones can add a bit of noise though.

**Comment by benfoley** [comment]
Out if interest and learning, which warnings would you typically ignore?

**Comment by oadams** [comment]
I'm going to re-open this issue as a reminder to address warnings.

**Comment by shuttle1987** [comment]
The errors are almost always serious problems and there's very few false positives. The warnings by contrast have more possibility of false positives or are less serious.  Here's the whole list along with comments:

W0101: Unreachable code
Important
W0102: Dangerous default value %s as argument
Important, indicates mutable default parameter bug potential
W0104: Statement seems to have no effect
Sometimes doesn't matter, usually indicative of dead code or some other issue
W0105: String statement has no effect
Sometimes doesn't matter, usually indicative of dead code or some other issue
W0106: Expression "%s" is assigned to nothing
Never seen this before, curious as to how this can come up.
W0107: Unnecessary pass statement
Not that important, but indicates a refactor to remove should be done.
W0108: Lambda may not be necessary
I've never seen this come up
W0109: Duplicate key %r in dictionary
Worth dealing with
W0110: map/filter on lambda could be replaced by comprehension
This is a bit of a stylistic thing, but has it's roots in performance
W0120: Else clause on loop without a break statement
Often indicates a bug.
W0121: Use raise ErrorClass(args) instead of raise ErrorClass, args.
Should change.
W0122: Use of exec
This is something that occasionally is good, if you are deliberately doing this it's likely worth explaining. mark it as ignored by pylint, it will show that you have thought about what you are doing.
W0141: Used builtin function %r
I need to look into this, I'm not sure exactly what this warning case is matching.
W0142: Used * or ** magic
This is a bit annoying actually, I think this should be a convention category and even then it's good to use this. Future python versions introducing more of such "magic" for unpacking shows that the community sentiment doesn't agree with this.
W0150: %s statement in finally block may swallow exception
Usually indicates bad code
W0199: Assert called on a 2-uple. Did you mean \'assert x,y\'?
Almost always needs to be fixed
W0201: Attribute %r defined outside __init__
This is a very good maintainability idea, don't define instance attributes outside __init__ in most circumstances as it is a readability hit. Sometimes this might be useful but again mark the pylint ignore on it if that comes up.
W0211: Static method with %r as first argument
Usually a bug if you have a staticmethod decorated function with "cls" or "self" as first argument. Not an pylint error because you could conceivably use that name but it would be a terrible naming choice.
W0212: Access to a protected member %s of a client class
Often a sign of a bad design, but this is a bit annoying as you do actually want to do this from time to time
W0221: Arguments number differs from %s method
Usually a bug
W0222: Signature differs from %s method
Usually a bug
W0223: Method %r is abstract in class %r but is not overridden
Worth more attention, iirc this might come up if pylint can't find the definition
W0231: __init__ method from base class %r is not called
Usually a bug
W0232: Class has no __init__ method
Often a bug if there's no metaclass magic going on.
W0233: __init__ method from a non direct base class %r is called
Often bug
W0234: iter returns non-iterator
Usually a bug
W0301: Unnecessary semicolon
Usually a refactor is good here
W0311: Bad indentation. Found %s %s, expected %s
W0312: Found indentation with %ss instead of %ss
W0331: Use of the <> operator
This operator doesn't even exist in Python 3, ancient code that's been out of favor for a long time
W0332: Use of "l" as long integer identifier
Another doesn't exist in python3 thing.
W0333: Use of the `` operator
I don't think I've ever seen this one
W0401: Wildcard import %s
Usually bad coding style. Is a bug in certain cases such as: https://www.lesinskis.com/TIL_python_imports.html
W0402: Uses of a deprecated module %r
Should be given attention
W0403: Relative import %r, should be %r
Usually important
W0404: Reimport %r (imported line %s)
Should be given attention
W0406: Module import itself
Usually a bug
W0410: __future__ import is not the first non docstring statement
Bug
W0511: (warning notes in code comments; message varies)
Not sure
W0512: Cannot decode using encoding "%s", unexpected byte at position %d
Usually bug
W0601: Global variable %r undefined at the module level
Usually bug
W0602: Using global for %r but no assigment is done
W0603: Using the global statement
Indicates code possibly able to be refactored, might be completely fine though.
W0604: Using the global statement at the module level
Usually bug
W0611: Unused import %s
Dead code potential
W0612: Unused variable %r
Dead code potential
W0613: Unused argument %r
Dead code potential
W0614: Unused import %s from wildcard import
Dead code potential
W0621: Redefining name %r from outer scope (line %s)
Often a bug, at the very least usually indicates code that could be cleaner
W0622: Redefining built-in %r
Sometimes you want to do this. If you haven't done it deliberately it's often a bug.
W0623: Redefining name %r from %s in exception handler
Often a bug, at the very least usually indicates code that could be cleaner
W0631: Using possibly undefined loop variable %r
Often bug
W0632: Possible unbalanced tuple unpacking with sequence%s: …
Often a bug. Indicates an unclear API usually.
W0633: Attempting to unpack a non-sequence%s
Bug except in really rare circumstances
W0701: Raising a string exception
This has been a type error since at least python 2.5, this is always a bug in modern python.
W0702: No exception type(s) specified
Usually a very bad idea, be as specific as possible with exceptions. No exception type specified catches *everything*.
W0703: Catching too general exception %s
Usually a bad idea
W0704: Except doesn't do anything
Usually a bug, always a sign of bad code
W0710: Exception doesn't inherit from standard "Exception" class
Usually a bad idea
W0711: Exception to catch is the result of a binary "%s" operation
W0712: Implicit unpacking of exceptions is not supported in Python 3
Bug
W1001: Use of "property" on an old style class
Bug in Python 2.x, old style classes don't exist in Python 3 so this won't come up.
W1111: Assigning to function call which only returns None
Usually bug
W1201: Specify string format arguments as logging function parameters
This is a strong antipattern because logging function parameters should be lazily evaluated as logging functions are only evaluated at a sufficiently high logging value. Eager evaluation can be a very severe premature pessimization
W1300: Format string dictionary key should be a string, not %s
Bug
W1301: Unused key %r in format string dictionary
Bug
W1401: Anomalous backslash in string: \'%s\'. String constant might be missing an r prefix.
Often bug
W1402: Anomalous Unicode escape in byte string: \'%s\'. String constant might be missing an r or u prefix.
Often bug
W1501: "%s" is not a valid mode for open.
Bug

**Comment by benfoley** [comment]
Thank you! An interesting read.

**Comment by shuttle1987** [comment]
I think this is mostly done now, I've been slowly chipping away at these issues in every PR. There's no errors left and most of the warnings have been dealt with as well.
