### ISSUE TITLE
Make Utterance a class?

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#161]
I suspect there's a variety of benefits that would come about from making Utterance a class with the various aspects of Python's data models that we could leverage.

For example you can define equality and various other methods that will let this data operate more nicely with Python's data model.

If we wanted to keep the memory footprint lower we can always profile then use `__slots__` or something similar.

What do you think?

**Comment by oadams** [comment]
I'm not an expert on these trade-offs but I don't think it's worth it. Utterance equality should work fine as it is, since the members are just strings, ints and Paths. There would be no real issue with memory footprint using classes, but I don't really see any meaningful gains. I like the immutability of the Utterance objects as they are.

If we were to do it then it would have to be very low priority on the list. Also, since Utterance objects aren't central to Corpus representations now anyway, there's less of a reason for it.

**Comment by shuttle1987** [comment]
Fair enough, I'll close this and we can reopen it later if we see value. I agree that the bigger concern is dealing with the Corpus side of things.
