### ISSUE TITLE
Corpus construction with no labels fails

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#202]
This has been reported:

> Yes. I found that if I were to create a new data folder which has no labels at all. The Corpus function would simply fail to run.
> I tried also to put in a few wavs and labels, and a few additional wavs without labels; this also failed because, I think, there are not enough wavs to create the training/testing/validation split.

**Comment by shuttle1987** [comment]
> I found that if I were to create a new data folder which has no labels at all. The Corpus function would simply fail to run.

I'm curious what the exact failure mode was here because it seems like something I'd be highly likely able to fix with a bit more info.

> I think, there are not enough wavs to create the training/testing/validation split.

There was an issue where there could be an empty testing or validation set if the overall labels set was small. I fixed this issue with the splits a while back in this commit https://github.com/persephone-tools/persephone/commit/63cd4408f2c20f2d6669669011603f1bd441c3e2.

I think it might be a good idea to log what the actual split percentages are as this just gets close to the 90%-5%-5% but won't actually exactly match that in many cases (especially with a small number of candidate labels).
