### ISSUE TITLE
harmonize license between Persephone and Elpis?

### ISSUE THREAD

**Issue by alexis-michaud** [persephone-tools/persephone#231]
Currently, persephone-tools/persephone is licensed under the GNU General Public License v3.0, whereas persephone-tools/elpis is licensed under the Apache License 2.0. Would there be a possibility to harmonize the license between the two tools, Persephone and Elpis?

The Apache license "explicitly states that it does NOT grant trademark rights, even though licenses without such a statement probably do not grant any implicit trademark rights". In case it is confirmed that there is no substantial difference, it would seem that there is no obstacle to convergence. 

Does anyone feel strongly about choosing one over the other? 

One of the topics to bring up with the Elpis team as part of plans for fullest interoperability?

**Comment by oadams** [comment]
Good point. I have no preference so I'm happy to change the License to Apache 2.0.

**Comment by shuttle1987** [comment]
As long as the license is compatible with the GPLv3 I'm fine with it.

A commentary about the interoperability is that I think the main issue is really a people and teams issue here. Getting real end user engagement with the development effort would be a *vastly* more cost effective way to build these tools. I'm more than happy to help out and donate some of my time as an open source maintainer if there's a faster and direct feedback loop with the users. The work that was done here when there was a direct dialogue between users and developers was very effective. Since this dialogue has ended I've found it very difficult to know what the actual pain points for users are and I'm very reluctant to work on a project without such a dialogue as this is a very ineffective and inefficient way to make software.

How might we make the communications easier between the users of the tools and the broader open source developer developer base?

**Comment by alexis-michaud** [comment]
Sounds like there is clear convergence in the thinking of the developers here! Clearly, that's the way to go: strong interactions between users & developers. 

As a user, one question that would come to mind at once is: At what date will a user interface (however preliminary) become available? At the Nov. 2019 workshop there was a great demo of [Persephone-ELAN](https://www.youtube.com/watch?v=-pDOEqRpZKs) to use Persephone in ELAN, as a plugin. But the user interface was not yet ready for carrying out the earlier step (creating the acoustic model, which is then used in ELAN): Elpis and Persephone interfaces are currently work in progress. So the potential users I know are basically waiting for an interface to be available. 

Here are three proposals. 

1) Announcing a date for a beta release, if at all possible?
If it could be announced that we're looking at a certain date for a beta version of a user interface, then I can imagine that colleagues would start preparing data sets & be interested to test & discuss all topics within linguists' reach. In addition to the 'heavy-duty' supporters (hi Nick! @nthieberger ) we could rustle up a bunch of motivated volunteers. I believe Guillaume Wisniewski ( @gw17 ) maintains a list of linguists who are keen to get started. Nathan Hill also has some thoughts & a 'waiting list' (including himself!)

2) Planning a workshop?
Could a date be set now for a workshop like the past Transcription Acceleration Project workshops? (it would be cool to hear Ben's thoughts @benfoley ) We could try to have it remotely, decreasing carbon footprint & expenses (we're improving teleworking skills by leaps & bounds these weeks, willy-nilly).

3) Planning publications?
Planning publications can be a good way to nudge researchers to get their act together ;-) If there were a plan to publish papers *about* interface development, it could help get a team to focus on the development work itself and develop + maintain a state-of-the-art tool, not?
Those could be (i) a paper in Joss, the [Journal of Open Science Software](https://joss.theoj.org/about) focusing on the computer-science side and (ii) a paper that's more intended for an audience of linguists.

Just my 2 cents! With warmest support.

PS Feel free to move this text to another area as appropriate, as it's broader than the current title of this Issue. What about expanding a Wiki section?

**Comment by shuttle1987** [comment]
In my mind there are a few things that would help this project at this point in time:

1. Easier communications between developers and end users
2. A clear goal for the project. What's the reason for this project to exist? What are the main goals?
3. More avenues for contributors to come on board
4. A way for us to consume our own product as this would make the development substantially more effective and faster
5. Releasing updates more frequently. This is especially so for bugfix and minor versions.
6. Some form of funding to get things moving again. Like last time I'd be more than happy to work on this project at a substantially discounted rate, however I want to see something completed in a short time frame if I'm to be heavily involved again and this will require direct communications with users.

> As a user, one question that would come to mind at once is: At what date will a user interface (however preliminary) become available?

At the moment there's no active development of Persephone so a date really can't be given at the moment. All time estimates hinge on understanding what's missing so starting a dialogue with users about this would help.

> So the potential users I know are basically waiting for an interface to be available.

What do they need and how might we get that line of communication opened?

> Announcing a date for a beta release, if at all possible?

I think announcing any sort of date would be extremely unhelpful at the moment, we need to get some sort of dialogue between users and developers first so that we know what issues are blocking people using the tool. Without knowledge of what is preventing people from currently using tool, giving any sort of calendar date for release will just be a wild guess.

> Planning a workshop?

This could be good at some point, the more engagement with users the better.

> Planning publications?

I think this is rather orthogonal to the issues of maintaining this library. I think a good goal is to get a usable tool up and running as soon as possible, if publications would help this either via new users or funding then I'd be in favor. For the most part I think a feature freeze would make sense at this point in time, happy to be pragmatic about this if the community were to benefit.
For example if there's some features or functionalities that would enable new publications then it would be great if they could join the conversation about this project. We may be able to accommodate new papers easily if the discussion can be started.

> What about expanding a Wiki section?

I'd be in favor of this. I think this is something that can be done on GitHub directly.


Effectively I think if we can get discussion moving we can get things back on track. Better knowledge transfer will help everyone, I'd be fairly strongly in favor of a chat room or Wiki for this project since many of the important discussions are non-programming in nature.

**Comment by oadams** [comment]
> Since this dialogue has ended I've found it very difficult to know what the actual pain points for users are and I'm very reluctant to work on a project without such a dialogue as this is a very ineffective and inefficient way to make software.

> What do they need and how might we get that line of communication opened?

What's needed right now has not changed from the fundamental requirement we previously identified: linguists need a simple bare bones UI that can be used to train a speech recognition model on their own data so that they can apply it to their untranscribed speech. The pain points with Persephone are that non-programmers have issues with a command line, therefore a working GUI needs to be available for wider adoption.

The code in persephone-frontend and persephone-web-API got tantalizingly close to being demo-able, but as of the end of 2018 a full model couldn't be trained because of front-end issues when uploading a realistic amount of utterances. In around November 2019 there was a workshop in London and as established in our email correspondence the front-end wasn't in a state to demo, and so I did the workshop using the command-line interface. That experience reiterated the absolute need for a GUI.

As per my email to you about this in January, the current plan has been to integrate Persephone with the Elpis frontend. Ben Foley maintains that project and is doing his PhD directly addressing the human-computer interface side of low-resource speech recognition. Since Ben's focus is complementary to the speech recognition modeling backend, it makes sense to work with the existing Elpis frontend (which currently can be run with a Kaldi backend and can handle ELAN files as input) and plug it into a Persephone backend. LACITO got funding for a developer based there in Paris (Benjamin Galliot) who has just in the last couple weeks started working on finishing this integration so that Elpis can tap into Persephone as well as Kaldi.

Meanwhile, over the last several years the world of speech recognition has continued to move on with the new era of end-to-end neural speech recognition continuing to improve (https://github.com/syhw/wer_are_we) and now maturely sitting alongside hybrid HMM-DNN models such as those implemented in Kaldi. With this wave of work a number of open source tools have emerged and matured. Some notable members of this family include ESPnet (https://github.com/espnet/espnet), wav2letter (https://github.com/facebookresearch/wav2letter) and DeepSpeech (https://github.com/mozilla/DeepSpeech).

With the pace of development in this area the question of the role of Persephone in the broader picture is an important one. At it's core it's an implementation of [Graves et al 2013 ](https://ieeexplore.ieee.org/abstract/document/6638947). A lot of work has been done in ASR models and also the available frameworks since then.

ESPnet was developed at Johns Hopkins, which is also where the pre-eminent hybrid ASR toolkit Kaldi was developed. ESPnet is compatible Kaldi's style of input data processing. This makes it a good candidate for being plugged into Elpis since Elpis already prepares data in the Kaldi format. ESPnet also has active development and includes a wide variety of model architectures. So there's no point competing.

With active development elsewhere of an ASR frontend specifically for linguists, and active development elsewhere of state-of-the-art speech recognition models, my focus has shifted to what is needed today: a connection between the two. So while Benjamin Galliot plugs Persephone into Elpis so that Persephone can become useable by more linguists, I've begun exploring plugging ESPnet into Elpis. Beyond just connecting the two pieces, this work will involve tweaking the models available in ESPnet so that they best work with the amount of training data linguist are likely to have (i.e. orders of magnitude less than what you'd find in benchmark corpora the models are developed against). This is likely the most fruitful path forward.

**Comment by benfoley** [comment]
Regarding the original question of license, to attempt to change the license of Elpis now would take another six months of negotiations with the university lawyers, which would not be a good use of time. If Persephone can change to Apache would be simplest from our point of view.

**Comment by benfoley** [comment]
Plugging Persephone into Elpis seems to be a good short-term approach to getting a GUI for Persephone out. There are certainly things that need to be done for Elpis to best accommodate different backends. It is surprising how Kaldi-specific (well, even Elan-specific) Elpis turns out to be is in spite of our best back-of-the-mind intentions of supporting different backends.

I suggest we aim to get Persephone+Elpis out in the short term, while continuing the user design process to build a GUI which more accurately reflects the work that Persephone users do. I wouldn't want to assume that the Elpis interface is necessarily the best for both phonemic and orthographic transcription needs. It may not end up being a radically different interface than the current Elpis one, but it's worth putting the effort in now to find out.

**Comment by shuttle1987** [comment]
> What's needed right now has not changed from the fundamental requirement we previously identified: linguists need a simple bare bones UI that can be used to train a speech recognition model on their own data so that they can apply it to their untranscribed speech. The pain points with Persephone are that non-programmers have issues with a command line, therefore a working GUI needs to be available for wider adoption.

This is good to know, I'll direct any of my efforts here for now.

If Elpis can create a frontend as well that's great, more alternatives is definitely better in these situations.

**Comment by oadams** [comment]
> Regarding the original question of license, to attempt to change the license of Elpis now would take another six months of negotiations with the university lawyers, which would not be a good use of time. If Persephone can change to Apache would be simplest from our point of view.

Ok, fair enough. In light of this we should just change the Persephone license to Apache 2.0.

**Comment by alexis-michaud** [comment]
OK great. 
So... what currently stands in the way of just changing the Persephone license to Apache 2.0? 
Just saying :-)

**Comment by shuttle1987** [comment]
I think this still needs changing:
https://github.com/persephone-tools/persephone/blob/cd8f27586fdaca1a812b8f6d3bc7be956f1dd4a1/setup.py#L10
