### ISSUE TITLE
Add type signatures to just about everything

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#90]
I say "just about" because there may be cases for not typing some things.

**Comment by shuttle1987** [comment]
Given that there's the `any` type, what would you want to not explicitly type?

**Comment by oadams** [comment]
I think the only time in an ideal world that I wouldn't add type annotations is when I'm figuring out the interface of something as I write it, or it's really a throwaway function (which I shouldn't commit anyway). In such cases the only reason I wouldn't annotate is going to be out of convenience, and using Any would undermine that. It's not that the code actually would be truly that generic in terms of its signature, and so in a way its a bit misleading to throw the Any in there.

In other cases (which are just about every other case) it seems it makes sense to minimize using Any. If we need to account for multiple types we can use type variables, Unions etc.

Thoughts?

**Comment by shuttle1987** [comment]
If something is a work in progress and you don't know what the interface is yet it's probably best to omit type information. I don't suspect you have anything __

**Comment by shuttle1987** [comment]
In #147 I added a significant number of types.

It's likely we will have a situation where we won't have complete coverage due to external libraries lacking stubs but despite this it has uncovered multiple bugs already.

Specifically the lack of Tensorflow stubs is quite annoying, I added multiple stubs but had to move on due to the amount of time it was taking. We can always disable the typecheck for library functions missing stubs via `# type: ignore` comments where necessary to keep project velocity up.

So I think overall adding in some type checking where it's easy to do so has a really good return on time invested.

**Comment by oadams** [comment]
Yeah, as discussed that was a reasonable move.

I'll leave this issue open though.

**Comment by shuttle1987** [comment]
I suspect this is a situation where opening up the stubs for Tensorflow for external contributions by splitting it out into a different repo might make a lot of sense. We are certainly not the only people who want mypy (.pyi) stubs for Tensorflow.

**Comment by shuttle1987** [comment]
We have most stuff covered now :tada:

**Comment by oadams** [comment]
:tada:

**Comment by shuttle1987** [comment]
Currently the `labels` arg to `Corpus.__init__` doesn't have the right type signature, it could be changed to `Set[str]` but then this would be in conflict with what is passed to `Corpus.determine_labels` which expects `Sequence[str]`. This has come up from looking at recent test case code.

**Comment by oadams** [comment]
Do you mean `Corpus.initialize_labels` instead of `Corpus.determine_labels`? `.initialize_labels` should take a Set[str] because it makes a uniqueness assumption in defining `label_to_index` anyway.
